#Can be edited online with https://editor.swagger.io/
swagger: "2.0"
info:
  description: Documentation de l'API publique d'Anotéa
  version: 1.0.0
  title: Anotea
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /api
schemes:
- https
- http
securityDefinitions:
  Authorization:
    type: apiKey
    in: header
    name: Authorization
    description: |
      Le header Authorization doit être de la forme suivante :

      Authorization: "ANOTEA-HMAC-SHA256 api_key:timestamp:digest"

      Le digest doit être crée en générant, à partir de vote secret, un HMAC SHA256 de la chaine de caractères composée des informations suivants concaténées dans l'ordre :

      digest = "timestamp + method + path + body"

      -timestamp :  Nombre de millisecondes depuis l'Unix Epoch UTC.
      -body : Le body de la requête (ex: json) ou rien s'il n'y a pas de body (ex: requête GET)
      -method: La méthode de la requête en upper case (ex: GET)
      -path : Le chemin de la route avec les parameters (ex: /api/v1/ping/authenticated?value=1)

      La durée de validité du digest est de 5 minutes.

      Exemple d'appel:
      curl -X GET \
        https://anotea.pole-emploi.fr/api/v1/ping/authenticated \
        -H 'Authorization: ANOTEA-HMAC-SHA256 admin:1532004499293:217e41887152c459e34bd7070ab1ac8da572c1cf6107cafbbd0217d4b87db1a4'
responses:
  AvisResponse:
    description: La liste des avis
    schema:
      type: object
      properties:
        avis:
          type: array
          items:
            $ref: "#/definitions/Avis"
        meta:
          type: object
          description: Informations complémentaires
          properties:
            pagination:
              $ref: "#/definitions/Pagination"

  AvisByIdResponse:
    description: Un avis
    schema:
      $ref: "#/definitions/Avis"

  SessionsResponse:
    description: La liste des sessions reconciliées
    schema:
      type: object
      properties:
        sessions:
          type: array
          items:
            $ref: "#/definitions/Session"
        meta:
          type: object
          description: Informations complémentaires
          properties:
            pagination:
              $ref: "#/definitions/Pagination"

  SessionByIdResponse:
    description: Une session avec ses avis reconciliées et son score
    schema:
      $ref: "#/definitions/Session"

  OrganismesFormateursResponse:
    description: La liste des organismes formateurs
    schema:
      type: object
      properties:
        avis:
          type: array
          items:
            $ref: "#/definitions/OrganismeFormateur"
        meta:
          type: object
          description: Informations complémentaires
          properties:
            pagination:
              $ref: "#/definitions/Pagination"

  OrganismeFormateurByIdResponse:
    description: Un organisme formateur
    schema:
      $ref: "#/definitions/OrganismeFormateur"

  GenerateAuthUrlResponse:
    description: Contient l'url permettant à l'organisme de s'authentifier en SSO sur Anotéa
    schema:
      $ref: "#/definitions/AuthUrl"

  UnauthorizedErrorResponse:
    description: Le header Authorization header est manquant ou invalide
    schema:
      $ref: "#/definitions/Error"

  BadRequestErrorResponse:
    description: Bad Request
    schema:
      $ref: "#/definitions/Error"

  NotFoundErrorResponse:
    description: Not Found
    schema:
      $ref: "#/definitions/Error"

definitions:
  Error:
    type: object
    properties:
      statusCode:
        type: integer
        example: 5xx/4xx
      error:
        type: string
        example: Internal Server Error
      message:
        type: string
        example: An internal server error occurred

  User:
    type: object
    properties:
      user:
        type: string
        description: Le nom de l'utilisateur ou l'apiKey

  Pagination:
    type: object
    description: Statut de la pagination
    properties:
      page:
        type: number
      items_par_page:
        type: number
      total_items:
        type: number
      total_pages:
        type: number

  Adresse:
    type: object
    properties:
      code_postal:
        type: string
      ville:
        type: string
      region:
        type: string

  Notes:
    type: object
    description: Moyenne des notes pour les avis
    properties:
      accueil:
        type: number
      contenu_formation:
        type: number
      equipe_formateurs:
        type: number
      moyen_materiel:
        type: number
      accompagnement:
        type: number
      global:
        type: number

  Score:
    type: object
    description: Score contenant le nombre d'avis et la moyenne de leurs notes
    properties:
      nb_avis:
        type: number
      notes:
        $ref: "#/definitions/Notes"

  Avis:
    type: object
    properties:
      id:
        type: string
        description: L'identifiant unique de l'avis
      pseudo:
        type: string
        description: Le pseudo du stagiaire
      date:
        type: string
        description: La date à laquelle l'avis a été crée
      commentaire:
        type: object
        properties:
          titre:
            type: string
          texte:
            type: string
      notes:
        $ref: "#/definitions/Notes"
      formation:
        description: La formation suivie par le stagiaire
        type: object
        properties:
          intitule:
            type: string
          domaine_formation:
            type: object
            properties:
              formacodes:
                type: array
                items:
                  type: string
          certifications:
            type: array
            uniqueItems: true
            minItems: 1
            items:
              properties:
                certif_info:
                  type: string
          action:
            type: object
            properties:
              lieu_de_formation:
                type: object
                properties:
                  code_postal:
                    type: string
                  ville:
                    type: string
              organisme_financeurs:
                type: array
                items:
                  type: string
              organisme_formateur:
                type: object
                properties:
                  raison_sociale:
                    type: string
                  siret:
                    type: string
              session:
                type: object
                properties:
                  numero:
                    type: string
                  periode:
                    type: object
                    properties:
                      debut:
                        type: string
                      fin:
                        type: string

  Session:
    type: object
    properties:
      id:
        type: string
        description: L'identifiant unique de la session
      numero:
        type: string
        description: Le numéro de la session
      avis:
        $ref: "#/definitions/Avis"
      meta:
        type: object
        description: Informations complémentaires
        properties:
          reconciliation:
            type: object
            description: Données relatives à la reconciliation
            properties:
              certifinfos:
                type: array
                items:
                  type: string
              formacodes:
                type: array
                items:
                  type: string
              lieu_de_formation:
                type: string
              organisme_formateur:
                type: string
          source:
            type: object
            description: Données relatives au catalogue utilisé comme source
            properties:
              numero_formation:
                type: string
              numero_action:
                type: string
              numero_session:
                type: string
              type:
                type: string
                description: Le type de catalague auxquel appartient la session
      score:
        $ref: "#/definitions/Score"

  OrganismeFormateur:
    type: object
    properties:
      id:
        type: string
        description: L'identifiant unique de l'organisme
      numero:
        type: string
        description: Le numéro de l'organisme
      siret:
        type: string
        description: Le SIRET de l'organisme
      region:
        type: array
        items:
          type: string
          description: La liste des régions dans lesquelles l'organisme réalise des formations
      raison_sociale:
        type: string
        description: La raison sociale de l'organisme
      lieux_de_formation:
        type: array
        items:
          type: object
          properties:
            adresse:
              $ref: "#/definitions/Adresse"
      score:
        $ref: "#/definitions/Score"

  AuthUrl:
    type: object
    properties:
      url:
        type: string
        description: L'url d'authentification pour l'organisme
      meta:
        type: object
        properties:
          organisme:
            type: object
            properties:
              siret:
                type: string
                description: Le siret de l'organisme qui est aussi son login
              raison_sociale:
                type: string
                description: Le raison sociale de l'organisme qui est aussi son login
              code_region:
                type: string
                description: Le code region de l'organisme qui est aussi son login


paths:
  /v1/avis:
    get:
      description: Renvoie tous les avis triés par date et filtrés en fonction des paramètres
      operationId: getAvis
      produces:
      - application/json
      parameters:
      - in: query
        name: organisme_formateur
        description: Le numéro SIRET de l'organisme formateur
        type: string
        required: false
      - in: query
        name: formacode
        description: Le formacode de la formation (Français appliqué=15226) ou un domaine de formation (Langues=152)
        type: string
        required: false
      - in: query
        name: certif_info
        description: Le certif info de la formation
        type: string
        required: false
      - in: query
        name: lieu_de_formation
        description: Le code postal du lieu de formation
        type: string
        required: false
      - in: query
        name: page
        description: Le numéro de la page
        type: number
        required: false
      - in: query
        name: items_par_page
        description: Le nombre d'avis par page
        type: number
        required: false
      responses:
        200:
          $ref: "#/responses/AvisResponse"
        400:
          $ref: "#/responses/BadRequestErrorResponse"
        401:
          $ref: "#/responses/UnauthorizedErrorResponse"

  /v1/avis/:id:
    get:
      description: >
        Permet d'obtenir un avis à partir de son identifiant
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        type: string
        required: true
      security:
      - Authorization: []
      responses:
        200:
          $ref: "#/responses/AvisByIdResponse"
        400:
          $ref: "#/responses/BadRequestErrorResponse"
        401:
          $ref: "#/responses/UnauthorizedErrorResponse"
        404:
          $ref: "#/responses/NotFoundErrorResponse"

  /v1/sessions:
    get:
      description: >
        Permet d'obtenir la liste de toutes les sessions contenues dans l'intercarif avec pour chacune d'elles, les avis réconciliés et le score.
        La réconcialition permet de rattacher des avis déposés sur des formations similaires.
        Une formation est considérée comme similaire si elle possède un organisme formateur (SIRET), un lieu de formation (code postal) et
        au moins un FORMACODE ou CERTIFINFOs identiquent à ceux de la formation dispensée durant la session.
      produces:
      - application/json
      parameters:
      - in: query
        name: id
        description: >
          Permet de limiter la recherche à un ou plusieurs identifiants de sessions
          L'identifiant d'une session à la forme suivante `numero_formation|numero_action|numero_session`
          (ex. `id=14_AF_0000011111|14_SE_0000102222|SE_0000102222`)
        type: string
        required: false
      - in: query
        name: numero
        description: Permet de limiter la recherche à un ou plusieurs numéros de sessions
        type: string
        required: false
      - in: query
        name: region
        description: Permet de limiter la recherche en filtrant le session en fonctiond de leur région
        type: string
        required: false
      - in: query
        name: nb_avis
        description: Permet de limiter la recherche renvoyant uniquement les sessions ayant un nombre d'avis égal ou supérieur à la valeur spécifiée
        type: string
        required: false
      - in: query
        name: fields
        description: Permet de projeter la session en selectionnant les champs renvoyés (ex. `fields=score,-avis`)
        type: number
        required: false
      - in: query
        name: page
        description: Le numéro de la page
        type: number
        required: false
      - in: query
        name: items_par_page
        description: Le nombre d'avis par page
        type: number
        required: false
      security:
      - Authorization: []
      responses:
        200:
          $ref: "#/responses/SessionsResponse"
        400:
          $ref: "#/responses/BadRequestErrorResponse"
        401:
          $ref: "#/responses/UnauthorizedErrorResponse"

  /v1/sessions/:id:
    get:
      description: >
        Permet d'obtenir une session à partir de son identifiant
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: >
          L'identifiant d'une session à la forme suivante `numero_formation|numero_action|numero_session`
           (ex. `id=14_AF_0000011111|14_SE_0000102222|SE_0000102222`)
        type: string
        required: true
      security:
      - Authorization: []
      responses:
        200:
          $ref: "#/responses/SessionByIdResponse"
        400:
          $ref: "#/responses/BadRequestErrorResponse"
        401:
          $ref: "#/responses/UnauthorizedErrorResponse"
        404:
          $ref: "#/responses/NotFoundErrorResponse"

  /v1/organismes-formateurs:
    get:
      description: >
        Permet d'obtenir la liste de tous les organismes formateurs contenus dans l'intercarif avec pour chacun d'eux leur score.
        Le score est calculé en prenant en compte l'intégralité des avis recueillis pour cet organisme.
      produces:
      - application/json
      parameters:
      - in: query
        name: id
        description: Permet de limiter la recherche à un ou plusieurs identifiants d'organismes
        type: string
        required: false
      - in: query
        name: numero
        description: Permet de limiter la recherche à un ou plusieurs numéros d'organismes
        type: string
        required: false
      - in: query
        name: siret
        description: Permet de limiter la recherche à un ou SIRETs d'organismes
        type: string
        required: false
      - in: query
        name: lieu_de_formation
        description: >
          Permet de limiter la recherche en filtrant les organismes ayant des formations dans des lieux de formation spécifiques
          Un lieu de formation peut être identifié par son code postal ou par sa région
        type: string
        required: false
      - in: query
        name: nb_avis
        description: Permet de limiter la recherche renvoyant uniquement les organismes ayant un nombre d'avis égal ou supérieur à la valeur spécifiée
        type: string
        required: false
      - in: query
        name: fields
        description: Permet de projeter l'organisme en selectionnant les champs renvoyés (ex. `fields=-lieux_de_formation,-organisme_responsable`)
        type: number
        required: false
      - in: query
        name: page
        description: Le numéro de la page
        type: number
        required: false
      - in: query
        name: items_par_page
        description: Le nombre d'avis par page
        type: number
        required: false
      security:
      - Authorization: []
      responses:
        200:
          $ref: "#/responses/OrganismesFormateursResponse"
        400:
          $ref: "#/responses/BadRequestErrorResponse"
        401:
          $ref: "#/responses/UnauthorizedErrorResponse"

  /v1/organismes-formateurs/:id:
    get:
      description: >
        Permet d'obtenir un organisme formateur à partir de son identifiant
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: >
          L'identifiant d'un organisme correspond à son numéro de SIRET
        type: string
        required: true
      security:
      - Authorization: []
      responses:
        200:
          $ref: "#/responses/OrganismeFormateurByIdResponse"
        400:
          $ref: "#/responses/BadRequestErrorResponse"
        401:
          $ref: "#/responses/UnauthorizedErrorResponse"
        404:
          $ref: "#/responses/NotFoundErrorResponse"

  /v1/ping/anonymous:
    get:
      description: Permet de vérifier que l'api fonctionne
      operationId: pingAnonymous
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: object
            properties:
              user:
                type: string
                description: L'utilisateur anonyme

  /v1/ping/authenticated:
    get:
      description: Permet de valider l'authentification
      operationId: pingAuthenticated
      produces:
      - application/json
      security:
      - Authorization: []
      responses:
        200:
          description: Successful
          schema:
            $ref: "#/definitions/User"

  /v1/ping/error:
    get:
      description: Permet de générer une erreur
      operationId: pingError
      produces:
      - application/json
      responses:
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"

  /backoffice/generate-auth-url:
    post:
      description: >
        Permet de générer un lien pour authentifier en SSO un organisme sur le backoffice Anotéa (signin).
        Si l'organisme n'est pas connu par Anotéa, il sera créé durant l'appel (signup)
      produces:
      - application/json
      parameters:
      - in: body
        name: payload
        required: true
        description: L'ensemble des informations permettant l'identification ou la création d'un organisme
        schema:
          type: object
          properties:
            filters:
              type: array
              items:
                type: object
                properties:
                  siret:
                    description: Le numéro SIRET de l'organisme formateur
                    type: string
                  raison_sociale:
                    type: string
                  courriel:
                    type: string
                  region:
                    type: string

      security:
      - Bearer: []
      responses:
        200:
          $ref: "#/responses/GenerateAuthUrlResponse"
        400:
          $ref: "#/responses/BadRequestErrorResponse"

